name: CI

on:
  workflow_dispatch:
  push:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: cargo fmt
        run: cargo fmt --all -- --check

      - name: cargo clippy
        run: cargo clippy

  examples:
    name: examples (${{ matrix.example }} / ${{ matrix.feature }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - example: toml_crossterm
            feature: crossterm_0_29_0
          - example: toml_crossterm_0_28_1
            feature: crossterm_0_28_1
          - example: yaml_termion
            feature: termion_4_0_6
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: cargo test
        run: cargo test --features ${{ matrix.feature }} -- --nocapture --format pretty

      - name: cargo build (example)
        run: cargo build --example ${{ matrix.example }} --features ${{ matrix.feature }}
